name: PSP Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pspdev/pspdev:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check PSP toolchain
        run: |
          psp-gcc --version
          psp-config --pspsdk-path
          pack-pbp --help

      - name: Build PSP game
        run: |
          make clean
          make

      - name: Check EBOOT.PBP
        run: |
          test -f EBOOT.PBP
          echo "EBOOT.PBP successfully created."

      - name: Upload EBOOT.PBP
        uses: actions/upload-artifact@v4
        with:
          name: Yenzangs-Trip-PSP
          path: EBOOT.PBP
